version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./your_path_to_laravel_project:/var/www/html
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./your_path_to_laravel_project:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: your_mysql_database
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_USER: your_mysql_user
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Redis Service
  # redis:
  #   image: redis:alpine
  #   container_name: laravel_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 